"use strict";
exports.HEROES = [
    { id: 1, name: 'Charles Xavier', xname: 'Professor X', powers: ['Professor X é um mutante nivel Alfa (apenas possuindo sua telepatia em nivel Omega), que possui vastos Poderes Telepáticos, e está entre os mais poderosos telepatas no Universo Marvel', 'Telepatia: Professor X é capaz de ler os pensamentos de outros ou projeta seus próprios pensamentos, dentro de um raio de aproximadamente 250 milhas (400 km). Ele pode aprender línguas estrangeiras através da leitura de língua localizada no centros do cérebro de alguém, e alternadamente "ensinar" outras línguas, para outras pessoas'], img_url: 'img/xavier.jpg' },
    { id: 2, name: 'Scott Summers', xname: 'Ciclope', powers: ['Rajadas Óticas: Capaz de projetar pura energia destrutiva de seus olhos de cor vermelho rubi. Suas rajadas não emitiam calor, mas fato já foi esclarecido, já que suas rajadas energéticas são abastecidas por energia solar e acabam retendo um pouco de seu calor. Como não possui controle sobre seus poderes, ele é obrigado a usar óculos especiais com barreira de quartzo rubi que impede o uso descontrolado de seus poderes'], img_url: 'img/ciclope.jpg' },
    { id: 3, name: 'Jean Grey', xname: 'Fênix', powers: ['Telecinese: É capaz de levitar, quebrar e mover objetos e pessoas somente com a força mental', 'Telepatia: Capacidade de ler mentes alheias e projetar seus próprios pensamentos nessas mesmas mentes, funciona num raio de 400 km. Com bastante esforço ela pode aumentar consideravelmente esse raio.'], img_url: 'img/fenix.jpg' },
    { id: 4, name: 'Ororo Munroe', xname: 'Tempestade', powers: ['Vôo: É a capacidade de flutuar pelos ares', 'Controle Climático: Habilidade de manipular o clima e dominar todos os seus elementos podendo criar tempestades, furacões, tornados, ciclones, maremotos, terremotos, chuvas, nevascas, neblina, entre outros. Ela tem poder o suficiente para destruir um continente inteiro.'], img_url: 'img/tempestade.jpg' },
    { id: 5, name: 'James "Logan" Howlett', xname: 'Wolverine', powers: ['Regeneração Celular: Regenera-se de ferimentos instantaneamente, sejam eles leves arranhões,cortes,tiros entre outros', 'Garras Metálicas: Mesmo não se referindo a um poder mutante em si, as garras de Logan são sua marca registrada por serem frequentemente utilizadas em combate. Wolverine possui 6 garras metálicas de 30 cm (3 em cada braço) que saem de seus antebraços com um comando mental. Essas garras, bem como seu esqueleto, foram recobertas artificialmente com o metal Adamantium', 'Sentidos Aguçados: É a capacidade de possuir seus sentidos melhorado podendo rastrear o alvo pelo cheiro, tendo também audição e visão superiores a de um humano normal.'], img_url: 'img/wolverine.jpg' },
    { id: 6, name: 'Anne Marie', xname: 'Vampira', powers: ['Força Aprimorada: Capacidade de exercer força física acima do normal. Entre os efeitos estão a habilidade de poder levantar grandes pesos ou esmiuçar materiais resistentes mediante o exercício de sua força física. Essa habilidade deve-se a absorção dos poderes da Miss Marvel', 'Vôo: Habilidade de propulsionar-se através do ar', 'Absorção de Poderes: Pode absorver o poder de outro mutante com contato físico com a pele e usar ele em si. Se o toque for prolongado ela pode matar a vítima ou roubar definitivamente seus poderes.'], img_url: 'img/vampira.jpg' },
    { id: 7, name: 'Hank McCoy', xname: 'Fera', powers: ['Super-Agilidade: É capaz de se mover rapidamente, e assim se tornando quase impossível de ser atingido por golpes. Pode andar pelas paredes e desviar de golpes que sejam desferidos contra ele', 'Sentidos Aguçados: Possui visão, olfato e audição apurados.'], img_url: 'img/fera.jpg' },
    { id: 8, name: 'Remy Lebeau', xname: 'Gambit', powers: ['Manipulação de Energia: O dom de canalizar e manipular energia caótica permite-lhe o poder de descargas de energia mística, afetando o inimigo de várias formas: ionizando, paralisando, ou só atingindo com rajadas, projéteis e explosões.'], img_url: 'img/gambit.jpg' },
    { id: 9, name: 'Jubilation Lee', xname: 'Jubileu', powers: ['Energia Plasmática: Capacidade de produzir energia plasmática destrutiva parecida com fogos de artifício com seus dedos que é forte o bastante para danificar aço.'], img_url: 'img/jubileu.jpg' }
];
//# sourceMappingURL=mock-heroes.js.map